[phases.setup]
nixPkgs = ["nodejs_22", "corepack"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@8.15.0 --activate",
  "pnpm install --no-frozen-lockfile --filter @raverpay/raverpay-admin"
]

[phases.build]
cmds = ["pnpm --filter @raverpay/raverpay-admin build"]

[start]
cmd = "pnpm --filter @raverpay/raverpay-admin start"
