[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile --filter @raverpay/raverpay-admin"]

[phases.build]
cmds = ["pnpm --filter @raverpay/raverpay-admin build"]

[start]
cmd = "pnpm --filter @raverpay/raverpay-admin start"
