[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "export NODE_OPTIONS='--max-old-space-size=6144'",
  "pnpm --filter @raverpay/raverpay-api prisma:generate",
  "pnpm --filter @raverpay/raverpay-api build"
]

[start]
cmd = "node apps/raverpay-api/dist/main.js"
